# The Fatimids and the Islamic West

Berkey, Jonathan. _The Formation,_ ch. 14, 130-40.

Heinz Halm. _Empire of the Mahdi: The Islamic Near East from the sixth to the eleventh century (3rd edition),_ tr. M. Bonner. Routledge, 2016, 1-22.

Daftary, Farhad. _A Short History of the Ismāʿīlīs._ Edinburgh, 1997, 63-119.

**Primary source:** 1) Al-Qāḍī al-Nuʿmān. _Iftitāḥ al-daʿwa,_ tr. Hamid
Haji as _Founding the Fatimid State: The Rise of an Early Islamic
Empire._ London and New York, 2006, 202-236 (the arrival of the Mahdi in
Ifrīqiya); 2) al-Muqaddasi. _Aḥsan al-taqāsim fī maʿrifat al-aqālīm,_
tr. B. Collins as _The Best Divisions for Knowledge of the Regions._
Reading, 1994, p. 203. (A description of Ṣabra al-Manṣūriyya, the
Fāṭimid capital near Qayrawān).

**Further reading:**

Bloom, Jonathan. _Arts of the City Victorious: Islamic Art and Architecture in Fatimid North Africa and Egypt._ New Haven and London, 2007, p. 37.

Brett, Michael. _The Fatimid Empire._ Edinburgh, 2017, 1-37.

Brett, Michael, and Elizabeth Fentress. _The Berbers._ Oxford, 1996.

Ivanow, Wladimir. _Ismaili Tradition Concerning the Rise of the Fatimids._ Oxford, 1942.