# Military states: Seljuqs, Ayyubids, Crusaders

M. Chamberlain, “Military Patronage States and the Political Economy of the Frontier, 1000–1250” in _A Companion to the History of the Middle East, ed. Y. Choueiri_ (Blackwell, 2005), pp. 135-53.

A.C.S. Peacock, “Seljuq Legitimacy in Islamic History” in _The Seljuqs: Politics, Society and Culture,_ eds. C. Lange & S. Mecit (Cambridge University Press, 2011), pp. 79-96. 

**Primary sources:**

Bahāʾ al-Dīn b. Shaddād, _The Rare and Excellent History of Saladin or al-Nawadir al-Sultaniyya wa'l-Mahasin al-Yusufiyya,_ transl. D.S. Richards (Routledge, 2002), selection.

Niẓām al-Mulk, _The book of government of rules for kings,_ transl. H. Darke (Routledge 2002), pp. 1-22 and 89-98.

**Further reading:**

A.C.S. Peacock, “Advice for the sultans of Rum: the ‘mirrors for princes’ of early thirteenth-century Anatolia” in Bill Hickman and Gary Leiser (eds), _Turkish Language, Literature and History: Travelers’ tales, sultans, and scholars since the eighth century_ (London: Routledge, 2016), pp. 276-307.

A. M. Eddé, Saladin (2014). 

